//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: dfsclient.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `DFSClientClient`, then call methods of this protocol to make API calls.
internal protocol DFSClientClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: DFSClientClientInterceptorFactoryProtocol? { get }

  func sayHello(
    _ request: Hello,
    callOptions: CallOptions?
  ) -> UnaryCall<Hello, Reply>
}

extension DFSClientClientProtocol {
  internal var serviceName: String {
    return "DFSClient"
  }

  /// Unary call to SayHello
  ///
  /// - Parameters:
  ///   - request: Request to send to SayHello.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func sayHello(
    _ request: Hello,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Hello, Reply> {
    return self.makeUnaryCall(
      path: DFSClientClientMetadata.Methods.sayHello.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSayHelloInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension DFSClientClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "DFSClientNIOClient")
internal final class DFSClientClient: DFSClientClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: DFSClientClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: DFSClientClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the DFSClient service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: DFSClientClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct DFSClientNIOClient: DFSClientClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: DFSClientClientInterceptorFactoryProtocol?

  /// Creates a client for the DFSClient service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: DFSClientClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol DFSClientAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: DFSClientClientInterceptorFactoryProtocol? { get }

  func makeSayHelloCall(
    _ request: Hello,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Hello, Reply>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension DFSClientAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return DFSClientClientMetadata.serviceDescriptor
  }

  internal var interceptors: DFSClientClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeSayHelloCall(
    _ request: Hello,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Hello, Reply> {
    return self.makeAsyncUnaryCall(
      path: DFSClientClientMetadata.Methods.sayHello.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSayHelloInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension DFSClientAsyncClientProtocol {
  internal func sayHello(
    _ request: Hello,
    callOptions: CallOptions? = nil
  ) async throws -> Reply {
    return try await self.performAsyncUnaryCall(
      path: DFSClientClientMetadata.Methods.sayHello.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSayHelloInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct DFSClientAsyncClient: DFSClientAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: DFSClientClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: DFSClientClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol DFSClientClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'sayHello'.
  func makeSayHelloInterceptors() -> [ClientInterceptor<Hello, Reply>]
}

internal enum DFSClientClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "DFSClient",
    fullName: "DFSClient",
    methods: [
      DFSClientClientMetadata.Methods.sayHello,
    ]
  )

  internal enum Methods {
    internal static let sayHello = GRPCMethodDescriptor(
      name: "SayHello",
      path: "/DFSClient/SayHello",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol DFSClientProvider: CallHandlerProvider {
  var interceptors: DFSClientServerInterceptorFactoryProtocol? { get }

  func sayHello(request: Hello, context: StatusOnlyCallContext) -> EventLoopFuture<Reply>
}

extension DFSClientProvider {
  internal var serviceName: Substring {
    return DFSClientServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "SayHello":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Hello>(),
        responseSerializer: ProtobufSerializer<Reply>(),
        interceptors: self.interceptors?.makeSayHelloInterceptors() ?? [],
        userFunction: self.sayHello(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol DFSClientAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: DFSClientServerInterceptorFactoryProtocol? { get }

  func sayHello(
    request: Hello,
    context: GRPCAsyncServerCallContext
  ) async throws -> Reply
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension DFSClientAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return DFSClientServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return DFSClientServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: DFSClientServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "SayHello":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Hello>(),
        responseSerializer: ProtobufSerializer<Reply>(),
        interceptors: self.interceptors?.makeSayHelloInterceptors() ?? [],
        wrapping: { try await self.sayHello(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

internal protocol DFSClientServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'sayHello'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeSayHelloInterceptors() -> [ServerInterceptor<Hello, Reply>]
}

internal enum DFSClientServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "DFSClient",
    fullName: "DFSClient",
    methods: [
      DFSClientServerMetadata.Methods.sayHello,
    ]
  )

  internal enum Methods {
    internal static let sayHello = GRPCMethodDescriptor(
      name: "SayHello",
      path: "/DFSClient/SayHello",
      type: GRPCCallType.unary
    )
  }
}
